name: Simple CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Just run tests to make sure nothing is broken
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json
      
      - name: Install dependencies
        run: |
          cd client && npm ci
          cd ../server && npm ci
      
      - name: Run client tests
        run: cd client && npm test
        
      - name: Run server tests  
        run: cd server && npm test
        
      - name: Build client (to catch build errors)
        run: cd client && npm run build

  # Only deploy if tests pass and it's main branch
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy
        run: |
          echo "🚀 Deploy to your hosting platform here"
          echo "Examples:"
          echo "- Deploy to Vercel/Netlify (frontend)"
          echo "- Deploy to Railway/Render (backend)"
          echo "- Or use platform CLI tools"
