name: Simple CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install client dependencies
        working-directory: ./queen-bee/client
        run: npm ci
        
      - name: Install server dependencies
        working-directory: ./queen-bee/server
        run: npm ci
      
      - name: Run client tests
        working-directory: ./queen-bee/client
        run: npm run test:run
        
      - name: Run server tests
        working-directory: ./queen-bee/server
        run: npm test
        
      - name: Build client
        working-directory: ./queen-bee/client
        run: npm run build
